import React from "react";
import ReactDOM from "react-dom/client";

//React Element
const heading = <h1 className="heading">Hello World!</h1>;

/**
 * Header Component
 *  - Logo Component
 *  - Navigation Component
 * Body Component
 *  - Search Input Component
 *  - Card Container Component
 *    - Restaurant Card Component
 *      - Image
 *      - Name of Res, Star, Rating, Cuisine, delivery time
 * Footer Component
 *  - Copyright Component
 *  - Social Media Icons Links Component
 *  - Address Component
 *  - Contact Component
 */

const soupsArr = [
  {
    item: {
      id: "ctl_544634559",
      name: "Clear Soup",
      price: 60,
      desc: "",
      min_price: 60,
      max_price: 60,
      default_price: 60,
      display_price: 60,
      variant_id: "v_741302857",
      parent_menu_id: "ctg_36954824",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 1,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: false,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "clearsoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [],
      info_tags: [],
      tag_slugs: ["veg", "services", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "clearsoup-soups-19011060",
      item_metadata:
        '{"v":741302857,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Clear Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812142",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634560",
      name: "Cream Of Mushroom Soup",
      price: 90,
      desc: "Cream of mushroom soup is a velvety and savory soup made with mushrooms, Vegetables, cream, and vegetable stock, seasoned with herbs and spices for depth of flavor.",
      min_price: 90,
      max_price: 90,
      default_price: 90,
      display_price: 90,
      variant_id: "v_741302858",
      parent_menu_id: "ctg_36954824",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 2,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: false,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "creamofmushroomsoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [],
      info_tags: [],
      tag_slugs: ["veg", "services", "sf-not-vegan", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services", "sf-not-vegan"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "creamofmushroomsoup-soups-19011060",
      item_metadata:
        '{"v":741302858,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Cream Of Mushroom Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812148",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634561",
      name: "Cream Of Veg Soup",
      price: 80,
      desc: "",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      variant_id: "v_741302859",
      parent_menu_id: "ctg_36954824",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 3,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: false,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "creamofvegsoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [],
      info_tags: [],
      tag_slugs: ["veg", "services", "sf-not-vegan", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services", "sf-not-vegan"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "creamofvegsoup-soups-19011060",
      item_metadata:
        '{"v":741302859,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Cream Of Veg Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812149",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634562",
      name: "Hot And Sour Soup",
      price: 80,
      desc: "Savory and tangy Chinese soup featuring a spicy broth filled with vegetables and sauces",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      variant_id: "v_741302860",
      parent_menu_id: "ctg_36954824",
      item_image_url:
        "https://b.zmtcdn.com/data/dish_photos/d4d/c6da1af6c55c93993ac42b82420aad4d.jpeg?output-format=webp",
      item_image_thumb_url:
        "https://b.zmtcdn.com/data/dish_photos/d4d/c6da1af6c55c93993ac42b82420aad4d.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 4,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: true,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "hotandsoursoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [
        {
          mediaType: "image",
          image: {
            url: "https://b.zmtcdn.com/data/dish_photos/d4d/c6da1af6c55c93993ac42b82420aad4d.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            data: null,
            bgColor: null,
            borderColor: null,
            bgColorHex: null,
            animation: null,
            animate: null,
            aspectRatio: null,
            type: null,
            height: null,
            width: null,
            clickAction: null,
            border: null,
            shouldIgnoreResizing: null,
            tracking: null,
            placeholderColor: null,
            heightRatio: null,
            scaleMode: null,
            filter: null,
            overlayTextData: null,
            overlayIcon: null,
            containerAnimations: null,
            overlayAnimation: null,
            offsetRatio: null,
            shouldExpand: null,
            cornerRadius: null,
            trackingData: null,
            gravity: null,
            repeatCount: null,
            themeConfig: null,
          },
          video: null,
          audio: null,
          lottie: null,
        },
      ],
      info_tags: [],
      tag_slugs: ["veg", "services", "sf-spicy", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services", "sf-spicy"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "hotandsoursoup-soups-19011060",
      item_metadata:
        '{"v":741302860,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Hot And Sour Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812146",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634563",
      name: "Manchow Soup",
      price: 80,
      desc: "Spicy and tangy Indo-Chinese soup made with mixed vegetables,  sauces, garnished with crispy noodles.",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      variant_id: "v_741302861",
      parent_menu_id: "ctg_36954824",
      item_image_url:
        "https://b.zmtcdn.com/data/dish_photos/3cb/0c41af9a52a2f148337e2085bb99a3cb.jpeg?output-format=webp",
      item_image_thumb_url:
        "https://b.zmtcdn.com/data/dish_photos/3cb/0c41af9a52a2f148337e2085bb99a3cb.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 5,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: true,
      visible: false,
      item_state: "available",
      rating: {
        total_rating_text: "12 votes",
        value: 4.23999977,
      },
      name_slug: "manchowsoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [
        {
          mediaType: "image",
          image: {
            url: "https://b.zmtcdn.com/data/dish_photos/3cb/0c41af9a52a2f148337e2085bb99a3cb.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            data: null,
            bgColor: null,
            borderColor: null,
            bgColorHex: null,
            animation: null,
            animate: null,
            aspectRatio: null,
            type: null,
            height: null,
            width: null,
            clickAction: null,
            border: null,
            shouldIgnoreResizing: null,
            tracking: null,
            placeholderColor: null,
            heightRatio: null,
            scaleMode: null,
            filter: null,
            overlayTextData: null,
            overlayIcon: null,
            containerAnimations: null,
            overlayAnimation: null,
            offsetRatio: null,
            shouldExpand: null,
            cornerRadius: null,
            trackingData: null,
            gravity: null,
            repeatCount: null,
            themeConfig: null,
          },
          video: null,
          audio: null,
          lottie: null,
        },
      ],
      info_tags: [],
      tag_slugs: ["veg", "services", "sf-spicy", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services", "sf-spicy"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "manchowsoup-soups-19011060",
      item_metadata:
        '{"v":741302861,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Manchow Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812143",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634564",
      name: "Noodles Soup",
      price: 90,
      desc: "",
      min_price: 90,
      max_price: 90,
      default_price: 90,
      display_price: 90,
      variant_id: "v_741302862",
      parent_menu_id: "ctg_36954824",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 6,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: false,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "noodlessoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [],
      info_tags: [],
      tag_slugs: ["veg", "services", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "noodlessoup-soups-19011060",
      item_metadata:
        '{"v":741302862,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Noodles Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812144",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634565",
      name: "Sweet Corn Soup",
      price: 80,
      desc: "Creamy and comforting Chinese-inspired soup made with fresh sweet corn kernels, mixed vegetables, and seasoned with gentle spices.",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      variant_id: "v_741302863",
      parent_menu_id: "ctg_36954824",
      item_image_url:
        "https://b.zmtcdn.com/data/dish_photos/f47/dbae9bcb490938af9438c48452604f47.jpeg?output-format=webp",
      item_image_thumb_url:
        "https://b.zmtcdn.com/data/dish_photos/f47/dbae9bcb490938af9438c48452604f47.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 7,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: true,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "sweetcornsoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [
        {
          mediaType: "image",
          image: {
            url: "https://b.zmtcdn.com/data/dish_photos/f47/dbae9bcb490938af9438c48452604f47.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            data: null,
            bgColor: null,
            borderColor: null,
            bgColorHex: null,
            animation: null,
            animate: null,
            aspectRatio: null,
            type: null,
            height: null,
            width: null,
            clickAction: null,
            border: null,
            shouldIgnoreResizing: null,
            tracking: null,
            placeholderColor: null,
            heightRatio: null,
            scaleMode: null,
            filter: null,
            overlayTextData: null,
            overlayIcon: null,
            containerAnimations: null,
            overlayAnimation: null,
            offsetRatio: null,
            shouldExpand: null,
            cornerRadius: null,
            trackingData: null,
            gravity: null,
            repeatCount: null,
            themeConfig: null,
          },
          video: null,
          audio: null,
          lottie: null,
        },
      ],
      info_tags: [],
      tag_slugs: ["veg", "services", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "sweetcornsoup-soups-19011060",
      item_metadata:
        '{"v":741302863,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Sweet Corn Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812145",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634566",
      name: "Tomato Soup",
      price: 100,
      desc: "Classic comfort food, known for its smooth texture and rich flavor derived from ripe tomatoes, herbs, and cream, served hot",
      min_price: 100,
      max_price: 100,
      default_price: 100,
      display_price: 100,
      variant_id: "v_741302864",
      parent_menu_id: "ctg_36954824",
      item_image_url:
        "https://b.zmtcdn.com/data/dish_photos/c30/5026568d5c4938b4f0bb139a906ebc30.jpeg?output-format=webp",
      item_image_thumb_url:
        "https://b.zmtcdn.com/data/dish_photos/c30/5026568d5c4938b4f0bb139a906ebc30.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 8,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: true,
      visible: false,
      item_state: "available",
      rating: {
        total_rating_text: "17 votes",
        value: 4.59000015,
      },
      name_slug: "tomatosoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [
        {
          mediaType: "image",
          image: {
            url: "https://b.zmtcdn.com/data/dish_photos/c30/5026568d5c4938b4f0bb139a906ebc30.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
            data: null,
            bgColor: null,
            borderColor: null,
            bgColorHex: null,
            animation: null,
            animate: null,
            aspectRatio: null,
            type: null,
            height: null,
            width: null,
            clickAction: null,
            border: null,
            shouldIgnoreResizing: null,
            tracking: null,
            placeholderColor: null,
            heightRatio: null,
            scaleMode: null,
            filter: null,
            overlayTextData: null,
            overlayIcon: null,
            containerAnimations: null,
            overlayAnimation: null,
            offsetRatio: null,
            shouldExpand: null,
            cornerRadius: null,
            trackingData: null,
            gravity: null,
            repeatCount: null,
            themeConfig: null,
          },
          video: null,
          audio: null,
          lottie: null,
        },
      ],
      info_tags: [],
      tag_slugs: ["veg", "services", "sf-not-vegan", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services", "sf-not-vegan"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "tomatosoup-soups-19011060",
      item_metadata:
        '{"v":741302864,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Tomato Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812147",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
  {
    item: {
      id: "ctl_544634567",
      name: "Veg Mushroom Soup",
      price: 90,
      desc: "Spicy and tangy Indo-Chinese soup made with mixed vegetables,  sauces, typically garnished with mushroom bits",
      min_price: 90,
      max_price: 90,
      default_price: 90,
      display_price: 90,
      variant_id: "v_741302865",
      parent_menu_id: "ctg_36954824",
      always_show_on_checkout: 0,
      is_bogo_active: false,
      order: 9,
      auto_add: 0,
      auto_add_quantity: 0,
      show_item_image: false,
      visible: false,
      item_state: "available",
      rating: null,
      name_slug: "vegmushroomsoup",
      free_dish_quantity: 0,
      item_type: "dish",
      added_bottom_text_field: null,
      modifier_group_ids: [],
      not_added_bottom_text_field: null,
      tracking_dish_type: "dish",
      disabled_text: null,
      media: [],
      info_tags: [],
      tag_slugs: ["veg", "services", "sf-spicy", "delivery-enabled"],
      service_slugs: ["delivery-enabled"],
      dietary_slugs: ["veg"],
      inapplicable_filter_tag_slugs: [],
      secondary_tag_slugs: ["services", "sf-spicy"],
      disclaimer_tag_slugs: [],
      entity_type: "catalogue",
      primary_tag_slug: "veg",
      food_legends: null,
      search_alias: "Soups",
      fb_slug: "vegmushroomsoup-soups-19011060",
      item_metadata:
        '{"v":741302865,"s_ctg":54198262,"cmb_sel":0,"cmb":0,"ff":false,"ctl_n":"Veg Mushroom Soup"}',
      added_bottom_text: "",
      not_added_bottom_text: "",
      not_added_bottom_text_color: "",
      remove_popup_text: "",
      item_auto_add_toast_message: "",
      item_auto_already_added_toast_message: "",
      remove_popup_title: "",
      vendor_item_id: "129812150",
      tag_ids: "1",
      item_tag_image:
        "https://b.zmtcdn.com/data/o2_assets/958e4cb4a8b255659daae2c430f976ea1608028693.png?output-format=webp",
      tag_images: [],
      tag_texts: [],
      tag_objects: [],
      hide_in_meals_menu: 1,
    },
  },
];

const Header = () => {
  return (
    <div className="header_container">
      <div className="logo_container">
        <img
          alt="image_link"
          className="logo"
          src="https://imgtr.ee/images/2024/07/25/83a63e84c4e01ed3e517d9d0fc6817e4.th.png"
        />
      </div>
      <div className="navigation_container">
        <ul className="navigation_links">
          <li>Home</li>
          <li>About Us</li>
          <li>Contact Us</li>
          <li>Cart</li>
        </ul>
      </div>
    </div>
  );
};

const Card = (props) => {
  const { item } = props.soupObj;
  const { name, price, min_price, rating } = item;
  console.log(name);
  return (
    <div className="card_container">
      <div className="image_container">
        <img src="https://b.zmtcdn.com/data/pictures/0/19011060/d2b4e06d60dc905655172d20da89af05_o2_featured_v2.jpg" />
      </div>
      <div className="about_item">
        <h3>{name}</h3>
        <p>Price: {price}</p>
        <p>Min Price: {min_price}</p>
        <p>Rating: 4.5/5</p>
        <p>Delivery Time: 30 mins</p>
      </div>
    </div>
  );
};

const Body = () => {
  return (
    <div className="body_container">
      <div className="search_container">
        <h3>Search</h3>
      </div>
      <div className="cards_container">
        {soupsArr.map((soup, index) => (
          <Card key={index} soupObj={soup} />
        ))}
      </div>
    </div>
  );
};

const AppLayout = () => {
  return (
    <div className="App-Layout">
      <Header />
      <Body />
    </div>
  );
};

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <>
    <AppLayout />
  </>
);
