const soupsArr = [
  {
    item: {
      id: "ctl_544634559",
      name: "Clear Soup",
      price: 60,
      desc: "",
      min_price: 60,
      max_price: 60,
      default_price: 60,
      display_price: 60,
      ratings: 4.8,
    },
  },
  {
    item: {
      id: "ctl_544634560",
      name: "Cream Of Mushroom Soup",
      price: 90,
      desc: "Cream of mushroom soup is a velvety and savory soup made with mushrooms, Vegetables, cream, and vegetable stock, seasoned with herbs and spices for depth of flavor.",
      min_price: 90,
      max_price: 90,
      default_price: 90,
      display_price: 90,
      ratings: 2.5,
    },
  },
  {
    item: {
      id: "ctl_544634561",
      name: "Cream Of Veg Soup",
      price: 80,
      desc: "",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      ratings: 4.2,
    },
  },
  {
    item: {
      id: "ctl_544634562",
      name: "Hot And Sour Soup",
      price: 80,
      desc: "Savory and tangy Chinese soup featuring a spicy broth filled with vegetables and sauces",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      ratings: 3.3,
    },
  },
  {
    item: {
      id: "ctl_544634563",
      name: "Manchow Soup",
      price: 80,
      desc: "Spicy and tangy Indo-Chinese soup made with mixed vegetables,  sauces, garnished with crispy noodles.",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      ratings: 3.1,
    },
  },
  {
    item: {
      id: "ctl_544634564",
      name: "Noodles Soup",
      price: 90,
      desc: "",
      min_price: 90,
      max_price: 90,
      default_price: 90,
      display_price: 90,
      ratings: 3.7,
    },
  },
  {
    item: {
      id: "ctl_544634565",
      name: "Sweet Corn Soup",
      price: 80,
      desc: "Creamy and comforting Chinese-inspired soup made with fresh sweet corn kernels, mixed vegetables, and seasoned with gentle spices.",
      min_price: 80,
      max_price: 80,
      default_price: 80,
      display_price: 80,
      ratings: 3.4,
    },
  },
  {
    item: {
      id: "ctl_544634566",
      name: "Tomato Soup",
      price: 100,
      desc: "Classic comfort food, known for its smooth texture and rich flavor derived from ripe tomatoes, herbs, and cream, served hot",
      min_price: 100,
      max_price: 100,
      default_price: 100,
      display_price: 100,
      ratings: 4.8,
    },
  },
  {
    item: {
      id: "ctl_544634567",
      name: "Veg Mushroom Soup",
      price: 90,
      desc: "Spicy and tangy Indo-Chinese soup made with mixed vegetables,  sauces, typically garnished with mushroom bits",
      min_price: 90,
      max_price: 90,
      default_price: 90,
      display_price: 90,
      ratings: 4.5,
    },
  },
];

export default soupsArr;
